name: Copy-rules-to-WCAG

on: 
  push:
    branches:
      - steve-action-test
    paths:
      - '/wcag-mapping.json'
      

jobs:
  cp-rules:
    # Name the Job
    name: Copy Rules file
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      -
      -name print 
      run: |
        wget https://raw.githubusercontent.com/w3c/wcag-act-rules/steve-action-test/wcag-mapping.json
        cat wcag-mapping.json
