name: Copy-rules-to-WCAG

on: 
  push:
    branches:
      - steve-action-test
    paths:
      - '/wcag-mapping.json'

jobs:
  copy-rules:
    name: Copy rules
    runs-on: ubuntu-latest
    steps:
      - name: Fetch file
        run: |
          wget https://raw.githubusercontent.com/w3c/wcag-act-rules/steve-action-test/wcag-mapping.json
          cat wcag-mapping.json
