name: Copy-rules-to-WCAG

# Commit a change to the ACT rules to the wcag repo, renaming it.
#
# Notes 
# - the ACT repo branch and file name need to be set in two places below
#  - in the on: trigger definition
#  - with the other configuration vars in env
# - A Personal Access Token (PAT) stores as a secret is required to push
#   - Suggest a specific W3C account it used for this rather a user account, so not accidently deleted
# - the git user name and useremail are provided and are shown in GitHub as who performed the commit.
# - GitHub shows a link in the commit message as link to the ACT repo commit so changes can be viewed

# github-actions
# github-actions@github.com

on: 
  push:
    branches:
      - steve-action-test
    paths:
      - 'wcag-mapping.json'

jobs:
  copy-rules:
    name: Copy rules
    runs-on: ubuntu-latest
    env:
      SOURCE_FILENAME: wcag-mapping.json
      DESTINATION_REPO: w3c/wcag
      DESTINATION_BRANCH: steve-action-test
      DESTINATION_FILENAME: act-mapping.json
      COMMIT_MESSAGE: ACT rules update from https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}
      WCAG_CLONE_DIR: wcag
    steps:
      - name: Clone and fetch file
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }} # add as PAT (https://github.com/settings/tokens) as a secret
        run: |
          echo "Cloning $DESTINATION_REPO git repository"
          git clone --single-branch --branch $DESTINATION_BRANCH "https://$API_TOKEN_GITHUB@github.com/$DESTINATION_REPO.git" "$WCAG_CLONE_DIR"  
          
          echo "Getting $SOURCE_FILENAME as $DESTINATION_FILENAME"
          cd "$WCAG_CLONE_DIR"
          SOURCE_URI="https://raw.githubusercontent.com/$GITHUB_REPOSITORY/${GITHUB_REF/refs\/heads\/}/$SOURCE_FILENAME"
          wget -P "$WCAG_CLONE_DIR" -O "$DESTINATION_FILENAME" "$SOURCE_URI"
       
      - name: Commit and Push
        run: |
          echo "Commit"
          cd "$WCAG_CLONE_DIR"
          git config user.name $GITHUB_ACTOR  
          git config user.email $GITHUB_ACTOR@w3c.org 
          git add .
          # check for changes with git diff-index to stop error
          git diff-index --quiet HEAD || git commit -m "$COMMIT_MESSAGE"
          
          echo "Push"
          git push origin --set-upstream "$DESTINATION_BRANCH"
