name: Copy-rules-to-WCAG

on: 
  push:
    branches:
      - steve-action-test
    paths:
      - 'wcag-mapping.json'

jobs:
  copy-rules:
    name: Copy rules
    runs-on: ubuntu-latest
    steps:
      - name: Clone and Fetch file
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }} # add as PAT (https://github.com/settings/tokens) as a secret
        run: |
          GIT_USER_EMAIL="stevelee@w3.org"
          GIT_USER_NAME="steve lee"
          WCAG_CLONE_DIR=wcag
          SOURCE_FILENAME="wcag-mapping.json"
          SOURCE_BRANCH="steve-action-test"
          SOURCE_REPO="w3c/wcag-act-rules"
          SOURCE_REPO_URI="https://raw.githubusercontent.com/$SOURCE_REPO/$SOURCE_BRANCH"
          DESTINATION_FILENAME="act-mapping.json"
          DESTINATION_BRANCH="steve-action-test"
          DESTINATION_REPO="w3c/wcag"
          COMMIT_MESSAGE="ACT rules update from https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"

          echo "Cloning $DESTINATION_REPO git repository"
          git clone --single-branch --branch $DESTINATION_BRANCH "$API_TOKEN_GITHUB@https://github.com/$DESTINATION_REPO.git" "$WCAG_CLONE_DIR"  
          
          echo "Getting $SOURCE_FILENAME as $DESTINATION_FILENAME"
          cd "$WCAG_CLONE_DIR"
          wget -P "$WCAG_CLONE_DIR" -O "$DESTINATION_FILENAME" "$SOURCE_REPO_URI/$SOURCE_FILENAME"
       
          echo "Commit"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          # check for changes with git diff-index
          git diff-index --quiet HEAD || git commit -m "$COMMIT_MESSAGE"
          
          echo "Push"
          git push origin --set-upstream "$DESTINATION_BRANCH"
