name: Copy-rules-to-WCAG

on: 
  push:
    branches:
      - steve-action-test
    paths:
      - '/wcag-mapping.json'


jobs:
  cp-rules:
    name: Copy Rules file
    runs-on: ubuntu-latest

    steps:
      -name: get file
      # wget the latest version of the file from GitHub rather than git checkout everything
      run: |
        wget https://raw.githubusercontent.com/w3c/wcag-act-rules/steve-action-test/wcag-mapping.json
        cat wcag-mapping.json
