name: Copy-rules-to-WCAG

on: 
  push:
    branches:
      - steve-action-test
    paths:
      - 'wcag-mapping.json'

jobs:
  copy-rules:
    name: Copy rules
    runs-on: ubuntu-latest
    steps:
      - name: CLone and Fetch file
        run: |
          # A modification of Action dmnemec /copy_file_to_another_repo_action 
          set -e
          # set -x
          GIT_USER_EMAIL="stevelee@w3.org"
          GIT_USER_NAME="steve lee"
          WCAG_CLONE_DIR=$(mktemp -d)
          SOURCE_FILENAME="wcag-mapping.json"
          SOURCE_BRANCH="steve-action-test"
          SOURCE_REPO="w3c/wcag-act-rules"
          SOURCE_REPO_URI="https://raw.githubusercontent.com/$SOURCE_REPO/$SOURCE_BRANCH"
          DESTINATION_FILENAME="act-mapping.json"
          DESTINATION_BRANCH="steve-action-test"
          DESTINATION_REPO="w3c/wcag"
          COMMIT_MESSAGE="ACT rules update from https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"

          echo "Cloning $DESTINATION_REPO git repository"
          git clone --single-branch --branch $DESTINATION_BRANCH "https://github.com/$DESTINATION_REPO.git" "$WCAG_CLONE_DIR"  
      
 #     - uses: actions/checkout@v2
 #       with:
 #         persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
 #         fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      
      - name: Create local changes
        run: |
          echo "Getting $SOURCE_FILENAME as $DESTINATION_FILENAME"
          cd "$WCAG_CLONE_DIR"
          wget -P "$WCAG_CLONE_DIR" -O "$DESTINATION_FILENAME" "$SOURCE_REPO_URI/$SOURCE_FILENAME"
      
      - name: Commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Add changes" -a
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
        # PAT from https://github.com/settings/tokens
          github_token: '44a76f1f66a240d1a06bfda0cb73291562080888'
          branch: ${{ github.ref }}
          repository: 'w3c/wcag'
